# Generated by Django 5.2.1 on 2025-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source_fp', models.FilePathField(verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Markdown content',
            },
        ),
    ]
