# Generated by Django 4.0.6 on 2025-05-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_mkdwn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markdowncontent',
            options={'verbose_name_plural': 'Markdown Content'},
        ),
    ]
